name: .NET Core

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  windowspublish:
    runs-on: windows-latest
    name: Windows Publish
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Windows Publish
        run: dotnet publish OpenTabletDriver.Installer.Wpf --configuration Release -p:PublishSingleFile=true -p:DebugType=embedded --self-contained false --runtime win-x64 --framework net5-windows -o build
      - name: Upload Wpf artifacts
        uses: actions/upload-artifact@master
        with:
          name: OpenTabletDriver.Installer
          path: build
